{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# دفتر واحد متكامل لتوليد بيانات افتراضية مع التقويم الهجري والميلادي\n",
        "### يشمل:\n",
        "- تثبيت واستخدام hijri_converter\n",
        "- تعريف دوال الإجازات للهجري والميلادي\n",
        "- تحميل بيانات الطقس وتخصيصها\n",
        "- توليد بيانات الدخول والخروج لأفراد الأسرة\n",
        "- حفظها في CSV"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "install-hijri-converter"
      },
      "outputs": [],
      "source": [
        "######################################################\n",
        "# 1) تثبيت مكتبة hijri_converter (في حال عدم تثبيتها)\n",
        "######################################################\n",
        "!pip install hijri-converter"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "setup-imports"
      },
      "outputs": [],
      "source": [
        "######################################################\n",
        "# 2) استيراد المكتبات وتعريف الدوال المساعدة\n",
        "######################################################\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import random\n",
        "import math\n",
        "from datetime import datetime, timedelta\n",
        "\n",
        "# مكتبة hijri_converter\n",
        "from hijri_converter import convert\n",
        "\n",
        "######################################################\n",
        "# دوال التحويل بين الهجري والميلادي\n",
        "######################################################\n",
        "def hijri_to_gregorian(h_year, h_month, h_day):\n",
        "    \"\"\"\n",
        "    تحويل تاريخ هجري إلى ميلادي باستخدام مكتبة hijri_converter.\n",
        "    تُعيد كائن datetime ميلادي (year, month, day).\n",
        "    \"\"\"\n",
        "    g = convert.Hijri(h_year, h_month, h_day).to_gregorian()\n",
        "    # g عبارة عن (year, month, day)\n",
        "    return datetime(g.year, g.month, g.day)\n",
        "\n",
        "def gregorian_to_hijri(g_date):\n",
        "    \"\"\"\n",
        "    تحويل تاريخ ميلادي datetime -> (سنة هجري, شهر, يوم) باستخدام hijri_converter\n",
        "    \"\"\"\n",
        "    h = convert.Gregorian(g_date.year, g_date.month, g_date.day).to_hijri()\n",
        "    # h = Hijri(year, month, day)\n",
        "    return (h.year, h.month, h.day)\n",
        "\n",
        "######################################################\n",
        "# تعريف العطل والإجازات (بالصيغة الميلادية)\n",
        "######################################################\n",
        "# يمكنك تعديل الفترات بناءً على التقويم الرسمي.\n",
        "\n",
        "student_holidays = [\n",
        "    # اليوم الوطني للطلاب 19-20 ربيع الأول 1446هـ -> بالميلادي 22-23 سبتمبر 2024\n",
        "    (datetime(2024, 9, 22), datetime(2024, 9, 23)),\n",
        "    \n",
        "    # نهاية الفصل الدراسي الأول 5 جمادى الأول 1446 -> 7 نوفمبر 2024 وتستمر 10 أيام\n",
        "    (datetime(2024, 11, 7), datetime(2024, 11, 16)),\n",
        "\n",
        "    # نهاية الفصل الدراسي الثاني 21 شعبان 1446 -> 20 فبراير 2025 وتستمر 11 يوم\n",
        "    (datetime(2025, 2, 20), datetime(2025, 3, 2)),\n",
        "\n",
        "    # إجازة عيد الفطر 20 رمضان 1446 -> 20 مارس 2025 وتستمر 17 يوم\n",
        "    (datetime(2025, 3, 20), datetime(2025, 4, 5)),\n",
        "\n",
        "    # إجازة عيد الأضحى 3 ذي الحجة 1446 -> 30 مايو 2025 وتستمر 16 يوم\n",
        "    (datetime(2025, 5, 30), datetime(2025, 6, 14)),\n",
        "\n",
        "    # إجازة منتصف العام 3 رجب 1446 -> 3 يناير 2025 تستمر 9 أيام\n",
        "    (datetime(2025, 1, 3), datetime(2025, 1, 11)),\n",
        "\n",
        "    # إجازات مطولة\n",
        "    (datetime(2024, 10, 17), datetime(2024, 10, 19)),\n",
        "    (datetime(2024, 12, 11), datetime(2024, 12, 12)),\n",
        "    (datetime(2025, 5, 4), datetime(2025, 5, 5)),\n",
        "]\n",
        "\n",
        "def is_student_holiday(date_m):\n",
        "    for start_h, end_h in student_holidays:\n",
        "        if start_h <= date_m <= end_h:\n",
        "            return True\n",
        "    return False\n",
        "\n",
        "employee_holidays = [\n",
        "    # اليوم الوطني 23 سبتمبر 2024\n",
        "    (datetime(2024, 9, 23), datetime(2024, 9, 23)),\n",
        "\n",
        "    # يوم التأسيس 22 فبراير 2025\n",
        "    (datetime(2025, 2, 22), datetime(2025, 2, 22)),\n",
        "\n",
        "    # عيد الفطر (1-4 أبريل 2025 تقريبًا)\n",
        "    (datetime(2025, 4, 1), datetime(2025, 4, 4)),\n",
        "\n",
        "    # عيد الأضحى (6-9 يونيو 2025 تقريبًا)\n",
        "    (datetime(2025, 6, 6), datetime(2025, 6, 9)),\n",
        "]\n",
        "\n",
        "def is_employee_holiday(date_m):\n",
        "    for start_h, end_h in employee_holidays:\n",
        "        if start_h <= date_m <= end_h:\n",
        "            return True\n",
        "    return False\n",
        "\n",
        "######################################################\n",
        "# تحميل بيانات الطقس\n",
        "######################################################\n",
        "def load_weather_data(filepath, city_name='qassim'):\n",
        "    \"\"\"\n",
        "    قراءة ملف الطقس وعزل بيانات المدينة المطلوبة.\n",
        "    يفترض أن الملف يحوي الأعمدة:\n",
        "    ['city','date','time','year','month','day','hour','minute','weather','temp','wind','humidity','barometer','visibility']\n",
        "    \"\"\"\n",
        "    df = pd.read_csv(filepath)\n",
        "    df = df[df['city'].str.lower() == city_name.lower()].copy()\n",
        "\n",
        "    def make_datetime(row):\n",
        "        return datetime(\n",
        "            int(row['year']),\n",
        "            int(row['month']),\n",
        "            int(row['day']),\n",
        "            int(row['hour']),\n",
        "            int(row['minute'])\n",
        "        )\n",
        "    df['datetime'] = df.apply(make_datetime, axis=1)\n",
        "    df['date_only'] = df['datetime'].dt.date\n",
        "    return df\n",
        "\n",
        "def get_weather_for_day(weather_df, date_obj):\n",
        "    \"\"\"\n",
        "    تعيد سجل طقس عشوائي لهذا اليوم (إن وجد).\n",
        "    date_obj: كائن تاريخ (date)\n",
        "    \"\"\"\n",
        "    same_day = weather_df[weather_df['date_only'] == date_obj]\n",
        "    if len(same_day) == 0:\n",
        "        return None\n",
        "    return same_day.sample(1).iloc[0].to_dict()\n",
        "\n",
        "def weather_reduces_chances(weather_str):\n",
        "    \"\"\"\n",
        "    إذا الطقس عاصفة رملية أو غبار، نقلل احتمالية الخروج مثلاً إلى 0.3.\n",
        "    \"\"\"\n",
        "    if weather_str is None:\n",
        "        return 1.0\n",
        "    w_lower = weather_str.lower()\n",
        "    if 'sandstorm' in w_lower or 'dust' in w_lower or 'storm' in w_lower:\n",
        "        return 0.3\n",
        "    else:\n",
        "        return 1.0"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## توليد البيانات الافتراضية في خلية واحدة\n",
        "سنقوم بالخطوات:\n",
        "1. تحديد الأفراد (`people`)\n",
        "2. تحديد نطاق التواريخ سنة كاملة\n",
        "3. تحميل ملف الطقس\n",
        "4. إنشاء سجلات الخروج/الدخول لكل فرد\n",
        "5. إضافة الضوضاء باستخدام توزيع طبيعي (gauss)\n",
        "6. مراعاة الطقس والعطل (موظفين وطلاب)\n",
        "7. حفظ النتيجة في CSV"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "generate-data"
      },
      "outputs": [],
      "source": [
        "######################################################\n",
        "# 3) توليد البيانات لسنة كاملة\n",
        "######################################################\n",
        "\n",
        "# 1) تحديد الأفراد\n",
        "people = [\"abdulmalik\", \"aseel\", \"sadeem\", \"amal\"]\n",
        "students = [\"abdulmalik\", \"aseel\", \"sadeem\"]\n",
        "employee = [\"amal\"]\n",
        "\n",
        "# 2) تحديد نطاق التواريخ سنة كاملة\n",
        "start_date = datetime(2024, 8, 1)\n",
        "days_num = 365\n",
        "date_list = [start_date + timedelta(days=i) for i in range(days_num)]\n",
        "\n",
        "# 3) تحميل ملف الطقس (عدّل المسار حسب موقع ملفك)\n",
        "weather_file_path = \"/Users/a1443/PSCS/SCS/EcooVision/weather-sa-2017-2019-clean.csv\"  # عدل اسم الملف أو المسار\n",
        "weather_df = load_weather_data(weather_file_path, city_name=\"Qassim\")\n",
        "print(\"Loaded weather records:\", len(weather_df))\n",
        "\n",
        "# 4) إنشاء السجلات\n",
        "all_records = []  # [person, event, timestamp, weather, temp, wind, humidity, NumDailyExits]\n",
        "\n",
        "for current_date in date_list:\n",
        "    day_of_week = current_date.weekday()  # Monday=0 ... Sunday=6\n",
        "    date_only = current_date.date()\n",
        "\n",
        "    chosen_weather = get_weather_for_day(weather_df, date_only)\n",
        "    weather_str = chosen_weather['weather'] if chosen_weather else None\n",
        "    weather_factor = weather_reduces_chances(weather_str)\n",
        "\n",
        "    # weekend: الجمعة=4, السبت=5\n",
        "    is_weekend = (day_of_week == 4 or day_of_week == 5)\n",
        "\n",
        "    # احتمال خروج جماعي\n",
        "    go_out_all_probability = 0.3 * weather_factor\n",
        "    go_out_all_together = False\n",
        "    if is_weekend and random.random() < go_out_all_probability:\n",
        "        go_out_all_together = True\n",
        "\n",
        "    # تعزيز إذا عطلة للطالب + الموظف\n",
        "    if is_student_holiday(current_date) and is_employee_holiday(current_date):\n",
        "        if random.random() < (0.5 * weather_factor):\n",
        "            go_out_all_together = True\n",
        "\n",
        "    for person in people:\n",
        "        # هل عنده دوام (طالب/موظف)؟\n",
        "        if person in students:\n",
        "            has_school = (day_of_week < 5) and (not is_student_holiday(current_date))\n",
        "        else:\n",
        "            has_school = (day_of_week < 5) and (not is_employee_holiday(current_date))\n",
        "\n",
        "        # 1) الدوام الأساسي (خروج وعودة)\n",
        "        if has_school:\n",
        "            if person == \"abdulmalik\":\n",
        "                exit_mean, exit_std = 7.5, 0.1\n",
        "                return_mean, return_std = 11.5, 0.1\n",
        "            elif person == \"aseel\":\n",
        "                exit_mean, exit_std = 7.5, 0.15\n",
        "                return_mean, return_std = 12.5, 0.2\n",
        "            elif person == \"sadeem\":\n",
        "                exit_mean, exit_std = 6.75, 0.1  # ~6:45\n",
        "                return_mean, return_std = 12.5, 0.15\n",
        "            elif person == \"amal\":\n",
        "                exit_mean, exit_std = 7.5, 0.1\n",
        "                return_mean, return_std = 12.5, 0.15\n",
        "            else:\n",
        "                exit_mean, exit_std = 7.5, 0.1\n",
        "                return_mean, return_std = 12.0, 0.1\n",
        "\n",
        "            exit_hour = random.gauss(exit_mean, exit_std)\n",
        "            return_hour = random.gauss(return_mean, return_std)\n",
        "\n",
        "            # تقييد الساعات ضمن 0-24\n",
        "            exit_hour = max(0, min(23.99, exit_hour))\n",
        "            return_hour = max(exit_hour + 1, min(23.99, return_hour))\n",
        "\n",
        "            exit_time = datetime(current_date.year, current_date.month, current_date.day) + timedelta(hours=exit_hour)\n",
        "            enter_time = datetime(current_date.year, current_date.month, current_date.day) + timedelta(hours=return_hour)\n",
        "\n",
        "            all_records.append([\n",
        "                person, \"Exit\", exit_time,\n",
        "                chosen_weather['weather'] if chosen_weather else None,\n",
        "                chosen_weather['temp'] if chosen_weather else None,\n",
        "                chosen_weather['wind'] if chosen_weather else None,\n",
        "                chosen_weather['humidity'] if chosen_weather else None,\n",
        "                None\n",
        "            ])\n",
        "            all_records.append([\n",
        "                person, \"Enter\", enter_time,\n",
        "                chosen_weather['weather'] if chosen_weather else None,\n",
        "                chosen_weather['temp'] if chosen_weather else None,\n",
        "                chosen_weather['wind'] if chosen_weather else None,\n",
        "                chosen_weather['humidity'] if chosen_weather else None,\n",
        "                None\n",
        "            ])\n",
        "\n",
        "        # 2) الخروج الإضافي (Shopping, Visiting)\n",
        "        extra_exits_num = np.random.poisson(0.7)\n",
        "        extra_exits_num = math.floor(extra_exits_num * weather_factor)\n",
        "        if extra_exits_num < 0:\n",
        "            extra_exits_num = 0\n",
        "\n",
        "        for i in range(extra_exits_num):\n",
        "            out_hour = random.gauss(17.0, 2.0)\n",
        "            out_hour = max(0, min(23.5, out_hour))\n",
        "\n",
        "            in_hour = out_hour + random.gauss(2.0, 0.5)\n",
        "            in_hour = max(out_hour + 0.5, min(23.9, in_hour))\n",
        "\n",
        "            out_time = datetime(current_date.year, current_date.month, current_date.day) + timedelta(hours=out_hour)\n",
        "            in_time = datetime(current_date.year, current_date.month, current_date.day) + timedelta(hours=in_hour)\n",
        "\n",
        "            all_records.append([\n",
        "                person, \"Exit\", out_time,\n",
        "                chosen_weather['weather'] if chosen_weather else None,\n",
        "                chosen_weather['temp'] if chosen_weather else None,\n",
        "                chosen_weather['wind'] if chosen_weather else None,\n",
        "                chosen_weather['humidity'] if chosen_weather else None,\n",
        "                None\n",
        "            ])\n",
        "            all_records.append([\n",
        "                person, \"Enter\", in_time,\n",
        "                chosen_weather['weather'] if chosen_weather else None,\n",
        "                chosen_weather['temp'] if chosen_weather else None,\n",
        "                chosen_weather['wind'] if chosen_weather else None,\n",
        "                chosen_weather['humidity'] if chosen_weather else None,\n",
        "                None\n",
        "            ])\n",
        "\n",
        "########################################\n",
        "# بناء DataFrame وإضافة NumDailyExits\n",
        "########################################\n",
        "df = pd.DataFrame(all_records, columns=[\n",
        "    \"PersonID\", \"Event\", \"Timestamp\", \n",
        "    \"Weather\", \"Temp\", \"Wind\", \"Humidity\", \n",
        "    \"NumDailyExits\"\n",
        "])\n",
        "\n",
        "df[\"Date\"] = df[\"Timestamp\"].dt.date\n",
        "\n",
        "exit_counts = df[df[\"Event\"]==\"Exit\"].groupby([\"PersonID\",\"Date\"]).size().reset_index(name=\"ExitCount\")\n",
        "df = df.merge(exit_counts, on=[\"PersonID\",\"Date\"], how=\"left\")\n",
        "\n",
        "df[\"NumDailyExits\"] = df[\"ExitCount\"]\n",
        "df.drop(columns=[\"ExitCount\"], inplace=True)\n",
        "\n",
        "df.sort_values(by=\"Timestamp\", inplace=True)\n",
        "df.reset_index(drop=True, inplace=True)\n",
        "\n",
        "print(\"\\n========================\")\n",
        "print(\"Data generation completed!\")\n",
        "print(\"Total records:\", len(df))\n",
        "print(\"Preview:\\n\", df.head(10))\n",
        "\n",
        "# حفظ في CSV\n",
        "output_file = \"synthetic_family_data_expanded.csv\"\n",
        "df.to_csv(output_file, index=False)\n",
        "print(f\"\\nSaved to {output_file}.\")"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "name": "single_notebook_synthetic_data.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}
