# Generated by Django 5.1.4 on 2024-12-16 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facerecognition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="activity",
            name="enter_date",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="exit_date",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="enter_date",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="exit_date",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
