# Generated by Django 5.1.4 on 2024-12-16 17:42

import facerecognition.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facerecognition", "0002_activity_date_alter_activity_enter_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image",
            field=models.ImageField(
                blank=True,
                default="person_placeholder.jpg",
                null=True,
                upload_to=facerecognition.models.define_image_path,
            ),
        ),
    ]
