# Generated by Django 5.1.4 on 2024-12-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facerecognition", "0003_alter_person_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="in_house",
            field=models.BooleanField(default=True),
        ),
    ]
