# Generated by Django 5.1.4 on 2024-12-16 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facerecognition", "0004_person_in_house"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="action",
        ),
        migrations.DeleteModel(
            name="Action",
        ),
    ]
