# Generated by Django 5.1.4 on 2024-12-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facerecognition", "0005_remove_activity_action_delete_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="action",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
