# Generated by Django 5.1.4 on 2024-12-17 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facerecognition", "0006_activity_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner",
                to="facerecognition.room",
            ),
        ),
    ]
